# This file is @generated by tarina.lang CLI tool
# It is not intended for manual editing.

from tarina.lang.model import LangItem, LangModel  # type: ignore[import-untyped]


class TlangCommand:
    set: LangItem = LangItem('tlang', 'command.set')


class Tlang:
    command = TlangCommand


class Lang(LangModel):
    tlang = Tlang
